//############################################################################//
const
{
key_f1 =129;
key_f2 =130;
key_f3 =131;
key_f4 =132;
key_f5 =133;
key_f6 =134;
key_f7 =135;
key_f8 =136;
key_f9 =137;
key_f10=138;
key_f11=139;
key_f12=140;
}

key_f1 =282;
key_f2 =283;
key_f3 =284;
key_f4 =285;
key_f5 =286;
key_f6 =287;
key_f7 =288;
key_f8 =289;
key_f9 =290;
key_f10=291;
key_f11=292;
key_f12=293;

key_0=48;
key_1=49;
key_2=50;
key_3=51;
key_4=52;
key_5=53;
key_6=54;
key_7=55;
key_8=56;
key_9=57;

key_a=97;
key_b=98;
key_c=99;
key_d=100;
key_e=101;
key_f=102;
key_g=103;
key_h=104;
key_i=105;
key_j=106;
key_k=107;
key_l=108;
key_m=109;
key_n=110;
key_o=111;
key_p=112;
key_q=113;
key_r=114;
key_s=115;
key_t=116;
key_u=117;
key_v=118;
key_w=119;
key_x=120;
key_y=121;
key_z=122;   

key_backspace=8;
key_tab=9;
key_space=32;
key_enter=13;
key_NUM_ENTER=913;
key_esc=27;   

key_lbrk=91;
key_rbrk=93;
key_equals=61;
key_minus=45;
key_plus=43;

key_comma=44;
key_dot=46;

key_right=275;
key_left=276;
key_up=273;
key_dwn=274;

key_gl_right=230;
key_gl_left=228;
key_gl_up=229;
key_gl_dwn=231;

key_pgup=280; //30;  //WTF?
key_pgdn=281; //31;  //WTF?
key_home=22;
key_end=23;
key_ins=28;
key_del=29;

key_star=42;
key_stroke=96;
key_slash=47;
key_backslash=92;
key_dualdot=59;  // ;

key_quote=39;

key_ctrl=306;
key_alt=308;
key_shift=304;
//############################################################################//
const
ukey_f1 =$E11A;
ukey_f2 =$E11B;
ukey_f3 =$E11C;
ukey_f4 =$E11D;
ukey_f5 =$E11E;
ukey_f6 =$E11F;
ukey_f7 =$E120;
ukey_f8 =$E121;
ukey_f9 =$E122;
ukey_f10=$E123;
ukey_f11=$E124;
ukey_f12=$E125;

ukey_ctrl_z=$1A;
ukey_ctrl_x=$18;
ukey_ctrl_c=$03; 
ukey_ctrl_v=$16;
ukey_ctrl_b=$02;
ukey_ctrl_n=$0E;
ukey_ctrl_r=18; 
ukey_ctrl_s=19;
ukey_ctrl_w=23;

ukey_ctrl_a=$01;

ukey_l_shift=$E130;
ukey_r_shift=$E12F;
ukey_l_ctrl=$E132;
ukey_r_ctrl=$E131;
ukey_l_alt=$E134;
ukey_r_alt=$E133;

ukey_caps=$E000;   //?
ukey_caps_b=$E12D;   //?
ukey_num=$E12C;
ukey_scroll=$E12E; //?  
 
ukey_pause=$E013;  
ukey_menu=$E13F;
ukey_win=$E137;

ukey_backspace=key_backspace;
ukey_tab=$E009;
ukey_space=key_space;
ukey_enter=key_enter;
ukey_num_enter=key_num_enter;
ukey_esc=key_esc;

ukey_left =$E114;
ukey_right=$E113;
ukey_up   =$E111;
ukey_dwn  =$E112; 

ukey_pgup=$E118;
ukey_pgdn=$E119;
ukey_home=$E116;
ukey_end =$E117; 
  
ukey_ins=$E115; 
ukey_del=$007F;


ukey_num_left =$E104;
ukey_num_right=$E106;
ukey_num_up   =$E108;
ukey_num_dwn  =$E102;

ukey_num_pgup=$E109;
ukey_num_pgdn=$E103;
ukey_num_home=$E107;
ukey_num_end =$E101;  

ukey_num_ins=$E100; 
ukey_num_del=$E10A;

ukey_num_5=$E105;
//############################################################################//
