//############################################################################//
const
key_F1=112;
key_F2=113;
key_F3=114;
key_F4=115;
key_F5=116;
key_F6=117;
key_F7=118;
key_F8=119;
key_F9=120;
key_F10=121;
key_F11=122;
key_F12=123;

key_a=65;
key_b=66;
key_c=67;
key_d=68;
key_e=69;
key_f=70;
key_g=71;
key_h=72;
key_i=73;
key_j=74;
key_k=75;
key_l=76;
key_m=77;
key_n=78;
key_o=79;
key_p=80;
key_q=81;
key_r=82;
key_s=83;
key_t=84;
key_u=85;
key_v=86;
key_w=87;
key_x=88;
key_y=89;
key_z=90;

key_0=48;
key_1=49;
key_2=50;
key_3=51;
key_4=52;
key_5=53;
key_6=54;
key_7=55;
key_8=56;
key_9=57;

key_backspace=8;
key_TAB=9;
key_SPACE=32;
key_ENTER=13;
key_NUM_ENTER=271;
key_ESC=27;
key_pause=19;

key_lbrk=219;   //[
key_rbrk=221;   //]
key_equals=187; //=+
key_minus=189;  //-_
key_comma=188;  //,<
key_dot=190;    //.>

key_left=37;
key_right=39;
key_up=38;
key_dwn=40;

key_gl_right=key_right;
key_gl_left=key_left;
key_gl_up=key_up;
key_gl_dwn=key_dwn;

key_pgup=33;
key_pgdn=34;
key_home=36;
key_end=35;
key_ins=45;
key_DEL=46;
key_stroke=192; //~
key_star=42; //*

key_dualdot=59; // ;
key_quote=39;  // '
key_backslash=92; // \
key_slash=47;    // /

key_ctrl=17;
key_alt=18;
key_shift=16;
//############################################################################//
const
ukey_f1 =$E03B;
ukey_f2 =$E03C;
ukey_f3 =$E03D;
ukey_f4 =$E03E;
ukey_f5 =$E03F;
ukey_f6 =$E040;
ukey_f7 =$E041;
ukey_f8 =$E042;
ukey_f9 =$E043;
ukey_f10=$E044;
ukey_f11=$E045;
ukey_f12=$E046;

ukey_ctrl_z=$1A;
ukey_ctrl_x=$18;
ukey_ctrl_c=$03;
ukey_ctrl_v=$16;
ukey_ctrl_b=$02;
ukey_ctrl_n=$0E;
ukey_ctrl_a=$01;

ukey_l_shift=$E02A;
ukey_r_shift=$E036;
ukey_l_ctrl=$E01D;
ukey_r_ctrl=$E11D;
ukey_l_alt=$E038;
ukey_r_alt=$E138;

ukey_caps=$E060;
ukey_caps_b=$E061;
ukey_num=$E145;
ukey_scroll=$E046; //?

ukey_pause=$E045;
ukey_menu=$E15D;
ukey_win=$E15B;

ukey_backspace=key_backspace;
ukey_tab=$E009;
ukey_space=key_space;
ukey_enter=key_enter;
ukey_num_enter=key_num_enter;
ukey_esc=key_esc;

ukey_left =$E14B;
ukey_right=$E14D;
ukey_up   =$E148;
ukey_dwn  =$E150;

ukey_pgup=$E149;
ukey_pgdn=$E151;
ukey_home=$E147;
ukey_end =$E14F;

ukey_ins=$E152;
ukey_del=$E153;


ukey_num_left =$E04B;
ukey_num_right=$E04D;
ukey_num_up   =$E048;
ukey_num_dwn  =$E050;

ukey_num_pgup=$E049;
ukey_num_pgdn=$E051;
ukey_num_home=$E047;
ukey_num_end =$E04F;

ukey_num_ins=$E052;
ukey_num_del=$E053;

ukey_num_5=$E04C;
//############################################################################//
